using Random
using Statistics
using Distributions

"""
Adaptive scaling Metropolis for θ only 

Fields

    post::Posterior                 Structure storing all variables needed
                                    to evaluate the posterior distribution

    θ0::Vector{Float64}             Initial state from which to start the
                                    markov chain

    iterations::Int                 Number of iterations for the MCMC loop 
                                    to perform. This is NOT the number of 
                                    accepted samples, but rather the number 
                                    of proposed samples.

    burnin::Int                     Number of generated samples to discard
                                    after the MCMC loop is complete

    thin::Int                       Frequency with which to keep post-burnin samples

    t0_adapt::Int                   Number of iterations to wait before adapting
                                    the proposal scheme

    target_accept::Real             Target for proportion of samples accepted during
                                    the MCMC loop

    rng_seed::Int                   Seed for the random number generator. Set to -1
                                    to use Random.default_rng()


Returns::NamedTuple, with fields
                        
    samples::Matrix{Float64}        Samples generated by the MCMC loop (post burnin 
                                    and thinning)

    logpost::Vector{Float64}        Log-posterior for each accepted sample

    Φ::Vector{Float64}              Empirical risk (W2 distance) for each accepted sample

    prop_accepted::Real             Proportion of ALL proposals (e.g. pre burnin and thinning)
                                    accepted during the MCMC loop
"""
function run_w2_chain(
    posterior::Posterior,
    θ0::Vector{Float64};
    iterations::Int=5000,
    burnin::Int=2500,
    thin::Int=2,
    t0_adapt::Int=100,
    target_accept::Real=0.44,
    rng_seed::Int=-1,
)

    # Select RNG
    if rng_seed == -1
        rng = Random.default_rng()
    else
        rng = Xoshiro(rng_seed)
    end

    # Allocate space for the samples
    # generated each iteration
    n_params = length(θ0)
    n_obs    = posterior.n_obs
    θ       = zeros(n_params, iterations+1)
    logpost = zeros(iterations+1)
    Φ       = zeros(n_obs, iterations+1)
    
    # Calculate initial posterior
    θ[:,1] .= θ0
    logpost[1], Φ[:,1] = log(posterior,θ0)

    # Variables for the proposal strategy
    μθ = θ0
    Σθ = 0.01 * Matrix(Diagonal(θ0))
    ηθ = 0.0
    γ = k -> (k + 1)^(-2/3)

    # BEGIN MCMC loop
    accept_theta = 0
    θ_curr = deepcopy(θ0)
    θ_prop = zero(θ_curr)
    logpost_curr = logpost[1]
    Φ_curr =  Φ[1]
    for iter in 1:iterations
        
        # Proposal for next sample
        θ_prop .= θ_curr + exp(ηθ) * sqrt(Σθ) * randn(rng, n_params) 

        # Posterior of the proposed sample
        logpost_prop, Φ_prop = log(posterior, θ_prop)

        # Accept the sample? 
        αθ = isfinite(logpost_prop) ? min(1.0, exp(logpost_prop - logpost_curr)) : 0.0
        if rand(rng) < αθ
            θ_curr .= θ_prop
            logpost_curr, Φ_curr = logpost_prop, Φ_prop
            accept_theta += 1
        end

        # Save iteration data
        θ[:,iter+1]       .= θ_curr
        logpost[iter+1]    = logpost_curr
        Φ[:,iter+1]       .= Φ_curr

        # Adapting the sample proposal scheme
        if iter >= t0_adapt
            dθ = θ_curr - μθ # vector
            μθ .+= γ(iter) * dθ # vector
            Σθ .+= γ(iter) * (dθ*transpose(dθ) - Σθ) # matrix
            Σθ .= max.(Σθ, 1e-10) # matrix
            ηθ += γ(iter) * (αθ - target_accept) # scalar
        end
    end

    # Discard samples within the burnin period and 
    # apply thinning to remaining samples
    kept = collect(burnin:thin:(iterations + 1))
    θ       = θ[:,kept]
    logpost = logpost[kept]
    Φ       = Φ[:,kept]

    # Package up into a CharacterizationEvent
    accept_ratio = accept_theta / iterations
    return CharacterizationEvent(posterior, θ, Φ, accept_ratio)
end
