using LinearAlgebra, QuantumGateDesign
include("QDT.jl")
include("events.jl")

"""
DigitalQudit struct

Represents a single digital qudit. Intended for evaluation and optimization 
of control pulses. 

Fields

    Ne:Int64                Number of essential energy levels

    Ng::Int64               Number of guard levels

    N::Int64                Total number of energy levels

    omega::Union{Float64, Vector{Float64}}        
                            
        Qudit frequency value or samples
        
    xi::Union{Float64, Vector{Float64}}           
                            
        Qudit self-kerr value or samples

    omega_rot::Float64      
    
        Rotating frame frequency

    control::AbstractControl

        Object to evaluate control amplitudes

"""
mutable struct DigitalQudit <: DigitalDevice

    Ne::Int64
    Ng::Int64
    N::Int64

    omega::Union{Float64, Vector{Float64}}
    xi::Union{Float64, Vector{Float64}}
    
    omega_rot::Float64
    control::AbstractControl 

    function DigitalQudit(
            Ne::Int64, 
            Ng::Int64, 
            omega::Union{Float64, Vector{Float64}}, 
            xi::Union{Float64, Vector{Float64}},
            omega_rot::Float64,
            control::AbstractControl
        )
        N = Ne + Ng
        new(Ne, Ng, N, omega, xi, omega_rot, control)
    end
end


"""
Creates a copy of this DigitalQudit
"""
function Base.copy(q::DigitalQudit)
    return DigitalQudit(
        q.Ne, q.Ng,
        copy(q.omega), copy(q.xi), 
        q.omega_rot, q.control
    )
end


"""
Sets the parameters (ω, ξ) of the DigitalQudit so they 
can be used for control evaluation and/or optimization.
"""
function set_parameters(q::DigitalQudit, ω::Float64, ξ::Float64)
    q.omega = ω
    q.xi    = ξ
end

function set_parameters(q::DigitalQudit, θ::Vector{Float64})
    q.omega = θ[1]
    q.xi    = θ[2]
end

function set_parameters(q::DigitalQudit, ω::Vector{Float64}, ξ::Vector{Float64})
    q.omega = copy(ω)
    q.xi    = copy(ξ)
end

function set_parameters(q::DigitalQudit, θ::Matrix{Float64})
    q.omega = θ[1,:]
    q.xi    = θ[2,:]
end


"""
Returns a copy of the current parameters of the DigitalQudit
as a single Matrix θ = [ω; ξ]
"""
function get_parameters(q::DigitalQudit)
    if isa(q.omega, Float64)
        return [q.omega; q.xi]
    else
        return [q.omega q.xi]
    end
end


"""
Returns the duration of the current control assigned to the DigitalQudit
"""
function get_control_time(self::DigitalQudit)
    return self.control.tf
end


########################################################################
# SIMULATION ROUTINES
########################################################################

"""
Returns a Vector of Matrices representing the drift
Hamiltonian (in the rotating frame) for each of this 
qudit's current parameter samples
"""
function get_drift_hamiltonians(q::DigitalQudit)

    # Set unscaled drift Hamiltonian
    a = lower_op(q.N) 
    H_omega = a' * a 
    H_xi = a' * a' * a * a;

    # Qudit parameters
    omega_rot = q.omega_rot;
    omega = q.omega
    xi = q.xi
    n_samples = length(omega)

    # Scaled Hamiltonians
    H_drift = [
        ((omega[j]-omega_rot)*H_omega) .- (0.5*xi[j]*H_xi)
        for j = 1:n_samples
    ]
    
    return H_drift
end


"""
Returns the (unscaled) control Hamiltonians a + a'
and a-a' for this qudit
"""
function get_control_hamiltonians(q::DigitalQudit)
    a = lower_op(q.N) 
    H_c_re = a + a';
    H_c_im = a - a';
    return H_c_re, H_c_im
end


"""
Returns a Vector of SchrodingerProb objects, one for each 
of this qudit's current parameter samples.

Argument 'T' specifies the time integration interval [0,T]
and dt is the stepsize.
"""
function get_schrodinger_problems(q::DigitalQudit, T, dt)
    
    # Initial state
    U0 = gate_initial_states(q.N, q.Ne)

    # Drift Hamiltonian by parameter sample
    H_drift = get_drift_hamiltonians(q)

    # Unscaled control Hamiltonian
    H_c_re, H_c_im = get_control_hamiltonians(q)

    # Number of timesteps
    n_timesteps = ceil(Int, T/dt)

    # Generating the SchrodingerProb
    probs = [  SchrodingerProb(
                    H_drift[j], [H_c_re], [H_c_im], 
                    U0, T, n_timesteps
                ) 
                for j in eachindex(H_drift)
            ]
    
    return probs
end


"""
Computes the state evolution Psi(t), for each of the qudit's current
parameter settings, in response to the control signal generated by 
the provided `control_coeffs`

Arguments

    q::DigitalQudit         Qudit on which to run the control 

    control_coeffs          Parameters (βs) of the control to execute

    dt::Float64             Integration step size    

"""
function run_control(q::DigitalQudit, control_coeffs::Vector{Float64}; 
                     dt::Float64=0.2)
    
    T_gate = q.control.tf
    
    # Create a SchrodingerProb for each of the qudits param samples
    probs = get_schrodinger_problems(q, T_gate, dt)  
    n_probs = length(probs)  
    n_timesteps = ceil(Int, T/dt) + 1

    # Run simulation for each parameter setting    
    Psi = zeros(Complex, n_probs, q.N, n_timesteps, q.Ne)
    for j = 1:n_probs
        state_history = QuantumGateDesign.eval_forward(probs[j], 
                                                       q.control, 
                                                       control_coeffs)
        Psi[j,:,:,:] .= state_history
    end

    return Psi
end



########################################################################
# Control Optimization
########################################################################


"""
Optimizes the control signals for this qudit to implement 
the provided gate

Arguments

    q::digital_qudit                DigitalDevice on which to simulate
                                    the response of the device to the
                                    control signals

    control_β0::Vector{Float64}     Initial/pre-optimized control parameters

    gate::GateType                  Which gate to optimize the controls for
    
    max_amplitude=0.1               Maximum (abs) value for each control param
    
    dt_opt = 0.2                    Simulation step size when optimizing the 
                                    control parameters
    
    dt_eval = 0.01                  Simulation step size when evaluating the 
                                    optimized control parameters
    
    options::Vector{Pair{String, Int64}}
                                    Options to be passed to IPOPT                         
"""
function optimize_control(
        q::DigitalQudit, 
        control_β0::Vector{Float64},
        gate::GateType; 
        max_amplitude=0.1,
        dt_opt = 0.2,
        dt_eval = 0.01,
        options=["max_iter" => 100, "print_level" => 3] 
    )
    
    T_gate = q.control.tf
    
    # Create a SchrodingerProb for each of the qudits param samples
    probs = get_schrodinger_problems(q, T_gate, dt_opt)
    n_probs = length(probs)    

    # Run the optimizer
    U_target = unitary(gate, q.N)
    opt_results = optimize_prob(
                            probs, q.control, control_β0, 
                            U_target, cost_type=:Infidelity,
                            pcof_lbound=-max_amplitude, 
                            pcof_ubound=max_amplitude, 
                            ipopt_options=options
                        )
    opt_coeffs = opt_results.x

    # Eval the final infidelities at each parameter    
    if dt_eval != dt_opt
        probs = get_schrodinger_problems(q, T_gate, dt_eval)
    end
    infidelities = zeros(n_probs)
    for j = 1:n_probs
        Psi = QuantumGateDesign.eval_forward(probs[j], q.control, opt_coeffs)[:,end,:]
        foreach(normalize!, eachcol(Psi))
        infidelities[j] = infidelity(Psi, U_target, q.Ne)
    end

    # Finalize results into a OptimizationEvent
    params = hcat(q.omega, q.xi)
    return OptimizationEvent(
                gate,
                get_parameters(q),
                opt_coeffs,
                infidelities,
                dt_opt, dt_eval
           )
end