#=
Functions for all DigitalDevices
=#



"""
Helper function for run_control() and optimize_control()

Determines the duration of the control signal given either a single
AbstractControl object or a Vector of AbstractControl objects.
"""
function control_duration(controller::Union{AbstractControl, Vector{AbstractControl}})
    if isa(controller, AbstractControl)
        return controller.tf
    else
        tf = controller[1].tf
        @assert all([tf == c.tf for c in controller])
        return controller[1].tf
    end
end



"""
Computes the state evolution Psi(t), for each of the qudit's current
parameter settings, in response to the control signal generated by 
the provided `control_coeffs`

Arguments

    q::DigitalDevice        Simulated device on which to run the control 

    controller              AbstractControl or Vector{AbstractControl}             

    control_coeffs          Parameters (βs) of the control to execute

    dt::Float64             Integration step size    

"""
@views function run_control(device::DigitalDevice, 
                     controller::Union{AbstractControl,Vector{AbstractControl}},
                     control_coeffs::Vector{Float64}; 
                     kwargs...)
    return run_control_base(device, controller, control_coeffs; kwargs...)
end


"""
Default `run_control()` implementation for `DigitalDevice` instances.
"""
@views function run_control_base(device::DigitalDevice, 
                     controller::Union{AbstractControl,Vector{AbstractControl}},
                     control_coeffs::Vector{Float64}; 
                     dt::Float64=0.2)

    T = control_duration(controller)
    
    # Create a SchrodingerProb for each of the qudits param samples
    probs = get_schrodinger_problems(device, T, dt)  
    n_probs = length(probs)  
    n_timesteps = ceil(Int, T/dt) + 1

    # Run simulation for each parameter setting    
    Psi = zeros(Complex, n_probs, device.N, n_timesteps, device.Ne)
    for j = 1:n_probs
        state_history = QuantumGateDesign.eval_forward(probs[j], 
                                                       controller, 
                                                       control_coeffs)
        Psi[j,:,:,:] .= state_history
        # Normalize states
        mat_Psi = reshape(view(Psi,j,:,:,:), device.N, :)
        mat_Psi ./= transpose(norm.(eachcol(mat_Psi)))
    end

    return Psi
end




"""
Optimizes the control signals for this device to implement the 
provided gate

Arguments

    device::DigitalDevice           DigitalDevice on which to simulate
                                    the response of the device to the
                                    control signals

    controller                      AbstractControl or Vector{AbstractControl}             

    control_β0::Vector{Float64}     Initial/pre-optimized control parameters

    gate::GateType                  Which gate to optimize the controls for
    
    max_amplitude=0.1               Maximum (abs) value for each control param
    
    dt_opt = 0.2                    Simulation step size when optimizing the 
                                    control parameters
    
    dt_eval = 0.01                  Simulation step size when evaluating the 
                                    optimized control parameters
    
    options::Vector{Pair{String, Int64}}
                                    Options to be passed to IPOPT                         
"""
function optimize_control(
        device::DigitalDevice, 
        controller::Union{AbstractControl,Vector{AbstractControl}},
        control_β0::Vector{Float64},
        gate::GateType; 
        kwargs...
    )
    return optimize_control_base(device, controller, control_β0, gate; kwargs...)
end


"""
Default `optimize_control()` implementation for `DigitalDevice` instances.
"""
@views function optimize_control_base(
        q::DigitalDevice, 
        controller::Union{AbstractControl,Vector{AbstractControl}},
        control_β0::Vector{Float64},
        gate::GateType; 
        max_amplitude=0.1,
        dt_opt = 0.2,
        dt_eval = 0.01,
        options=["max_iter" => 100, "print_level" => 3] 
    )
    
    T_gate = control_duration(controller)
    
    # Create a SchrodingerProb for each of the qudits param samples
    probs = get_schrodinger_problems(q, T_gate, dt_opt)
    n_probs = length(probs)    

    # Run the optimizer
    U_target = unitary(gate, q.N)
    opt_results = optimize_prob(
                            probs, controller, control_β0, 
                            U_target, cost_type=:Infidelity,
                            pcof_lbound=-max_amplitude, 
                            pcof_ubound=max_amplitude, 
                            ipopt_options=options
                        )
    opt_coeffs = opt_results.x

    # Eval the final infidelities at each parameter    
    if dt_eval != dt_opt
        probs = get_schrodinger_problems(q, T_gate, dt_eval)
    end
    infidelities = zeros(n_probs)
    for j = 1:n_probs
        Psi = QuantumGateDesign.eval_forward(probs[j], controller, opt_coeffs)[:,end,:]
        foreach(normalize!, eachcol(Psi))
        infidelities[j] = infidelity(Psi, U_target, q.Ne)
    end

    # Finalize results into a OptimizationEvent
    return OptimizationEvent(
                gate,
                get_parameters(q),
                controller,
                opt_coeffs,
                infidelities,
                dt_opt, dt_eval
           )
end


